export enum QuestionType {
  CHOOSE_PRODUCT = 'CHOOSE_PRODUCT',
  CHOOSE_PRICE = 'CHOOSE_PRICE',
  MATCHING_PRICE = 'MATCHING_PRICE',
  UP_OR_DOWN = 'UP_OR_DOWN',
  SORT_BY_PRICE = 'SORT_BY_PRICE',
}
